# Generated by Django 6.0 on 2025-12-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_department_alter_user_role'),
        ('core', '0002_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='faculties', to='core.subject'),
        ),
    ]
